# Generated by Django 2.1.7 on 2019-03-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.IntegerField(default=0)),
                ('frequency_total', models.IntegerField(default=0)),
            ],
        ),
    ]
