# Generated by Django 2.1.7 on 2019-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='id',
        ),
        migrations.AlterField(
            model_name='words',
            name='text',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
