# Generated by Django 2.1.7 on 2019-03-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0002_auto_20190305_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='text',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
